// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  x: __t.i16(),
  y: __t.i16(),
  biomTyp: __t.u8(),
  kraeuterMenge: __t.u8(),
  spiritStones: __t.u8(),
  holz: __t.u8(),
  erz: __t.u8(),
};
