// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  name: __t.string(),
  qi: __t.u64(),
  qiMaximum: __t.u64().name("qi_maximum"),
  stufe: __t.u8(),
  posX: __t.f32().name("pos_x"),
  posY: __t.f32().name("pos_y"),
});
