// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Credential = __t.object("Credential", {
  playerId: __t.u64(),
  passwordHash: __t.string(),
});
export type Credential = __Infer<typeof Credential>;

export const EditorSecret = __t.object("EditorSecret", {
  id: __t.u32(),
  passwordHash: __t.string(),
});
export type EditorSecret = __Infer<typeof EditorSecret>;

export const EditorSession = __t.object("EditorSession", {
  owner: __t.identity(),
  authorized: __t.bool(),
});
export type EditorSession = __Infer<typeof EditorSession>;

export const LoginAttempt = __t.object("LoginAttempt", {
  playerId: __t.u64(),
  success: __t.bool(),
});
export type LoginAttempt = __Infer<typeof LoginAttempt>;

export const Player = __t.object("Player", {
  playerId: __t.u64(),
  name: __t.string(),
  qi: __t.u64(),
  qiMaximum: __t.u64(),
  stufe: __t.u8(),
  posX: __t.f32(),
  posY: __t.f32(),
});
export type Player = __Infer<typeof Player>;

export const WorldMeta = __t.object("WorldMeta", {
  id: __t.u32(),
  generiert: __t.bool(),
  seed: __t.i32(),
  breite: __t.i16(),
  hoehe: __t.i16(),
});
export type WorldMeta = __Infer<typeof WorldMeta>;

export const WorldTile = __t.object("WorldTile", {
  tileId: __t.u32(),
  x: __t.i16(),
  y: __t.i16(),
  biomTyp: __t.u8(),
  noiseWert: __t.f32(),
  kraeuterMenge: __t.u8(),
  spiritStones: __t.u8(),
  holz: __t.u8(),
  erz: __t.u8(),
});
export type WorldTile = __Infer<typeof WorldTile>;

