// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tileId: __t.u32().primaryKey().name("tile_id"),
  x: __t.i16(),
  y: __t.i16(),
  biomTyp: __t.u8().name("biom_typ"),
  noiseWert: __t.f32().name("noise_wert"),
  kraeuterMenge: __t.u8().name("kraeuter_menge"),
  spiritStones: __t.u8().name("spirit_stones"),
  holz: __t.u8(),
  erz: __t.u8(),
});
