// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DurchbruchReducer from "../durchbruch_reducer";
import EditorLoginReducer from "../editor_login_reducer";
import EditTileReducer from "../edit_tile_reducer";
import LoginReducer from "../login_reducer";
import QiSammelnReducer from "../qi_sammeln_reducer";
import RegisterReducer from "../register_reducer";
import SetEditorPasswordReducer from "../set_editor_password_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type DurchbruchParams = __Infer<typeof DurchbruchReducer>;
export type EditorLoginParams = __Infer<typeof EditorLoginReducer>;
export type EditTileParams = __Infer<typeof EditTileReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type QiSammelnParams = __Infer<typeof QiSammelnReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type SetEditorPasswordParams = __Infer<typeof SetEditorPasswordReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

